name: Auto Merge Approved PRs to Develop

on:
  pull_request:
    types: [opened, reopened, ready_for_review, labeled, unlabeled, synchronize]

permissions:
  pull-requests: write
  contents: write

jobs:
  automerge:
    if: ${{ github.event.pull_request.base.ref == 'develop' && github.actor != 'github-actions[bot]' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Enable Auto-Merge on PR
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
