name: Auto Merge to Develop

on:
  pull_request:
    types: [labeled, synchronize, opened, reopened, ready_for_review]

permissions:
  pull-requests: write
  contents: write

jobs:
  automerge:
    if: github.event.pull_request.base.ref == 'develop' && github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # ✅ Recommended for full repo context

      - name: Enable Auto-Merge for PR
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
